### ISSUE TITLE
Add a way to preserve already existing translations

### ISSUE THREAD

**Issue by tagoro9** [APSL/redux-i18n#37]
Right now I'm using the `translations` prop in the `I18n` component, but I would like to use the reducer to keep the translations. 

The problem is that in a project I'm working on, the translations are loaded partially (by route) and there is also a set of translations that are loaded all the time. If I wanna use the `setTranslations` action, this cannot be achieved, as the initial shared translations will be deleted by the route translations. So, I would like to have a way to merge translations (within a language) instead of replacing them.

Does it make sense to have such a feature?

I can work on this, but since there are different approaches to solve the problem, I would like to get some guidance on which option to implement (if it makes sense to add this feature) before I get started. Some ideas that I have:

* Add an option to the existing `setTranslations` action. This involves some refactor. Since both `language` and a possible new parameter `preserveExisting` are optional (method signature would change to something like `setTranslations(translations, {language, preserveExisting})`, but this method is not compatible with the existing signature so we would have to check if the second arg is a string (language) or an object (new way) and it doesn't feel totally right.
* Preserve the translations as a default. This is fine, but it may brake the existing functionality for certain users (Not quite sure of this).
* Add a new public `mergeTranslations` action that merges the new translations with the existing ones. 

Can you think of any other possibilities?

Thank you very much.

**Comment by francescarpi** [comment]
Thank you for your contributions. This is a great suggestion and I think thats important do it.

I'm not sure what is the best solution, neither. 

I discard preserve translations as default, because not all people will want this functionality.

Add a new public mergeTranlsations action doesn't the better option, because there are repeated code and I'm not totally convinced.

I think that the best solution is add a third param at setTranslations and evaluate if language is a string or boolean and put business logic there.

Besides, I like that all code about this funcionality is inside setTranslations.

If you develop this functionality I'll very grateful because I've a lot of work, now. Remember add unit tests.

Thank you so much.

**Comment by tagoro9** [comment]
Thanks so much for your reply. I'll work on this this week.
